site_name: Geocodificador ICGC
site_url: 'http://ejemplo.com'
site_description: Documentació i exemples Geocodificador ICGC
theme:
  name: material
  language: 'ca'
  logo: img/ICGC_color_norma.svg
  favicon: img/favicon.ico
  palette: 
      primary: custom
      accent: custom
  features:
      - navigation.tabs
      - navigation.instant.prefetch
      - navigation.expand
      - content.code.copy
extra_css:
  - 'stylesheets/extra.css'

repo_url: 'https://github.com/nombreusuario/proyectourlongithub'
edit_uri: edit/master
markdown_extensions:
  - attr_list
  - md_in_html   
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences 
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
    
  
nav:
- Inici: 
  - Geocodificador ICGC: index.md
- Operacions:  
  - cerca: parametres_cerca.md
  - autocompletar: parametres_autocompletar.md
  - invers: parametres_invers.md
- Exemples:  
  - 1.1 Cercar una adreça: ex_adreca.md
  - 1.2 Cercar un topònim: ex_toponim.md
  - 1.3 Geocodificació inversa: ex_invers.md
  - 1.4 Obtenir el llogaret al que pertany una adreça: ex_llogaret1.md
  - 1.5 Cercar una adreça postal segons el llogaret: ex_llogaret2.md
  - 1.6 Integració en un visor Leaflet: visor.md
  - 1.7 Prioritzar els resultats més propers a un punt: ex_prioritzar.md
  - 1.8 Restringir la cerca dins una àrea geogràfica circular o rectangular: ex_area.md
  - 1.9 Filtrar segons tipus de topònim: ex_tipus.md
  - 1.10 Filtrar per comarca o per municipi: ex_comarca_municipi.md
- Visor: visor.md
- Referències: 
  - Tipus de topònims: tipusToponims.md





