site_name: Geocodificador ICGC
# produccio
#site_url: https://openicgc.github.io/geocodificador-doc
site_url: http://127.0.0.1:8000/geocodificador-doc
site_description: Documentació i exemples servei Geocodificador ICGC
extra:
  alternate:
  #    ## Original Language pip install mkdocs-google-translate
    - name: Català
      lang: ca
      link: ' https://openicgc.github.io/geocodificador-doc/'
    - name: Español
      lang: es
      link: ' https://openicgc.github.io/geocodificador-doc_es/'
theme:
  name: 'material'
  language: ca
  logo: 'assets/icgc_gencat_logos_blanc.png'
  favicon: assets/favicon.png
  palette:  
    - scheme: custom
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Canviar a mode fosc
    - scheme: slate
      primary: custom   
      toggle:
        icon: material/brightness-4
        name: Canviar a mode clar

  #highlightjs: true
  # hljs_style: github
  # nav_style: dark
  #suppress_nextprev: true
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.path
    # - navigation.instant.prefetch
      - navigation.expand
      - content.code.copy
extra_css:
  - 'stylesheets/extra.css'

#edit_uri: edit/master
markdown_extensions:
  #- codehilite:
      #linenums: True
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  #- pymdownx.critic
  #- pymdownx.caret
  #- pymdownx.keys
  #- pymdownx.mark
  #- pymdownx.tilde
  #- pymdownx.details
  - footnotes
  - tables
  - attr_list  
  

#repo_url: https://github.com/OpenICGC/geocodificador-doc
#repo_url: "https://autogitlab.icgc.local/i.fabrellas/geocodificador_mkdocs"
repo_url: "https://github.com/OpenICGC/geocodificador-doc"

nav:
- Inici: 
  - Geocodificador ICGC: index.md
- Operacions:  
  - Cerca directa completa: parametres_cerca.md
  - Cerca directa autocompletar: parametres_autocompletar.md
  - Cerca inversa: parametres_invers.md
- Documentació: documentacio.md
- Exemples:  
  - 1.1 Cercar una adreça: ex_adreca.md
  - 1.2 Cercar un topònim: ex_toponim.md
  - 1.3 Geocodificació inversa: ex_invers.md
  - 1.4 Obtenir el llogaret al que pertany una adreça: ex_llogaret1.md
  - 1.5 Cercar una adreça postal segons el llogaret: ex_llogaret2.md
  - 1.6 Integració en un visor Leaflet: ex_visor.md
  - 1.7 Prioritzar els resultats més propers a un punt: ex_prioritzar.md
  - 1.8 Restringir la cerca dins una àrea geogràfica circular o rectangular: ex_area.md
  - 1.9 Filtrar segons tipus de topònim: ex_tipus.md
  - 1.10 Filtrar per comarca o per municipi: ex_comarca_municipi.md
- Visor: visor.md
- Referències: 
  - Tipus de topònims: tipusToponims.md

plugins:
  - search
      

          
            







